### ISSUE TITLE
eth-testrpc installation error on Mac. Fatal error: 'openssl/aes.h' file not found

### ISSUE THREAD

**Issue by MeLoco1** [ConsenSys/eth-testrpc#32]
I tried to install with
`pip install eth-testrpc`

and it failed with:

crypt-1.1.6/lib/crypto/crypto_aesctr.c:38:10: fatal error: 'openssl/aes.h' file not found
    #include <openssl/aes.h>
             ^
    1 error generated.
    error: command '/usr/bin/clang' failed with exit status 1

log: https://gist.github.com/MeLoco1/347f2e69a08c82a11247

OS: OS X El Capitan 10.11.2
Python 2.7.10

**Comment by tcoulter** [comment]
Hi @MeLoco1. Have you tried using [ethereumjs-testrpc](https://github.com/ethereumjs/testrpc) instead of the python version? I'm the main developer and maintainer of both, however I've since put my effort into the Javascript version as I've found the APIs better and the http server more stable. If you can, give ethereumjs-testrpc a shot and let me know how it goes. Note, you'll need to `pip uninstall eth-testrpc` before installing the javascript version.

**Comment by MeLoco1** [comment]
Thank you @tcoulter.
ethereumjs-testrpc is perfect for me.

**Comment by tcoulter** [comment]
Sweet! Thanks for the update.

**Comment by MeLoco1** [comment]
Can you mention it in README.md?
